### PR TITLE
OpenYGE - fix to support v3 frame header extension

### PR DESCRIPTION
**Pull request by bob01**
Fix required for OpenYGE telemetry  v3 frames which may appear with YGE FW release.
It was necessary to extend the header which will cause a compatibility issue unless addressed.

### CODE REVIEW

**Comment by rotorflight** [comment]
All PRs into the master branch, please.

**Comment by bob01** [comment]
Np - thought bug fixes went to release and things not meant for the pending releasee went to master - closing...

**Comment by rotorflight** [comment]
Generally speaking, anything going into the release branches must be first validated in the master branch, usually by people testing a snapshot made from the master, or a test package. Once we are happy that everything is totally fine with the commit, then we can consider adding it to the release branch.

**Comment by rotorflight** [comment]
Is the YGE FW release using v3 format, and some earlier test versions are using v1 and v2?
If so, is it worth keeping v1 and v2 around? Any reason for people to not update to the YGE release?

**Comment by bob01** [comment]
There is a strong possibility at this point if the YGE FW release will be v3+ but uncertain.
The v3 data frame is significant because it is a header extension which breaks existing listener implementations (RF).
YGE FW snapshot 1.03547 (v2) is already in the public domain outside the test group (unexpected) - have to assume there will be a mix of v2 and v3+ plus around for some time.

**Comment by bob01** [comment]
Testing of this fix was limited to small number of subjects (3 helis, 2 pilots) w/ YGE FW 1.03547 prior to submission of the PR.

**Comment by rotorflight** [comment]
Okay... That's rather poor development practise from YGE.
No problem. We can keep them.

**Review by rotorflight — APPROVED** [review]

**Pull request merged**
