### PR TITLE
Added CRSF reuse targets crsf_gps_heading_reuse, crsf_gps_ground_speed_reuse, crsf_gps_altitude_reuse

### PR DESCRIPTION
**Pull request by bob01**
Added the CRSF reuse targets below...

Needed for more complex Tx telemetry for cases where existing 3 numeric crsf_att_* targets are insufficient e.g. on larger models where rx/bec voltage monitor w/ alarms etc in addition to std gov performance monitors are common.
Branch based on Snapshot 4.3.0-20240128

Notes:
- reuses attributes in the CRSF GPS frame
- GPS frame is added to schedule if any of the crsf_gps_*_reuse targets is enabled
- method .getVoltageMeter(...) was shifted above .crsfFrameGps(...) for reuse but otherwise unchanged
- .crsfGpsReuse(...) was based on .crsfAttitudeReuse(...) with 1/10 scaling factor applied for EdgeTx sensor ratios in line with crsf_att_*_reuse targets for *_VOLTAGE values
- changes to .crsfFrameGps(....) were kept to a minimum
- added supporting enums, structures, table entries to settings.c
e.g. LOOKUP_TABLE_ENTRY(lookupTableCrsfGpsReuse), valueTable etc.
====

crsf_gps_heading_reuse = NONE
Allowed values: NONE, MCU_TEMP, MCU_LOAD, SYS_LOAD, RT_LOAD, BEC_VOLTAGE, BUS_VOLTAGE, MCU_VOLTAGE

crsf_gps_ground_speed_reuse = NONE
Allowed values: NONE, MCU_TEMP, MCU_LOAD, SYS_LOAD, RT_LOAD, BEC_VOLTAGE, BUS_VOLTAGE, MCU_VOLTAGE

crsf_gps_altitude_reuse = NONE
Allowed values: NONE, MCU_TEMP, MCU_LOAD, SYS_LOAD, RT_LOAD, BEC_VOLTAGE, BUS_VOLTAGE, MCU_VOLTAGE

EdgeTx telemetry sensor ratios are the same as for the crsf_att_*_reuse targets...
- BEC_VOLTAGE, BUS_VOLTAGE, MCU_VOLTAGE = 20
- MCU_LOAD, SYS_LOAD, RT_LOAD = 0

image

### CODE REVIEW

**Comment by rotorflight** [comment]
Looks like you are still adding new things to this PR.
Please let us know when it is ready to be reviewed.

**Comment by rotorflight** [comment]
What's the situation with EdgeTx 2.9.3 now?
Are the GPS reuse options working correctly, and scaling correctly?

**Comment by bob01** [comment]
EdgeTx 2.9.3 - the sources in this PR are ok.
HEADSPEED was added and tested yesterday as gps_heading, gps_ground_speed and gps_altitude - with ratios 850.0, 8500.0 and 85.0 respectively. That commit is on another branch as I'd promised that this PR was done
I'll submit that branch shortly.

This has been tested on 4 helis with BEC_VOLTAGE as gps_heading and PROFILE_INDEX (Bank) as gps_sats

**Comment by rotorflight** [comment]
This PR wasn't based on the devel branch, so I merged it manually.

**Comment by bob01** [comment]
Sorry about branch mix up - I've resubmitted the brach with the added HEADSPEED source (single commit) based on devel for an easier review/merge

**Pull request closed without merging**
